[project]
name = "sim_to_motec"
dynamic = ["dependencies"]

version = "1.6.0"

requires-python = ">=3.9"

[tool.setuptools]
py-modules = ["stm"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
