[project]
name = "sim-to-motec"
dynamic = ["dependencies"]

version = "1.6.0"

requires-python = ">=3.9"

[tool.setuptools]
py-modules = []
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
